#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

KEYSTORE_PROPS="$ROOT_DIR/keystore.properties"
if [[ ! -f "$KEYSTORE_PROPS" ]]; then
  echo "ERROR: Missing keystore.properties in project root."
  echo "Create it from keystore.properties.example and set real values."
  exit 1
fi

if [[ -z "${JAVA_HOME:-}" ]] && [[ -d "$ROOT_DIR/.tools/jdk-21.0.10+7" ]]; then
  export JAVA_HOME="$ROOT_DIR/.tools/jdk-21.0.10+7"
fi

if [[ -n "${JAVA_HOME:-}" ]]; then
  export PATH="$JAVA_HOME/bin:$PATH"
fi

echo "==> Running tests and building signed release bundle"
./gradlew --no-daemon :core:test :app:testDebugUnitTest :app:bundleRelease

AAB_PATH="$ROOT_DIR/app/build/outputs/bundle/release/app-release.aab"
if [[ ! -f "$AAB_PATH" ]]; then
  echo "ERROR: Release bundle not found at $AAB_PATH"
  exit 1
fi

STAMP="$(date +%Y%m%d-%H%M%S)"
OUT_DIR="$ROOT_DIR/release-artifacts/$STAMP"
mkdir -p "$OUT_DIR"

cp "$AAB_PATH" "$OUT_DIR/"
COPIED_AAB="$OUT_DIR/app-release.aab"

VERSION_CODE="$(grep -E '^app.versionCode=' "$ROOT_DIR/gradle.properties" | cut -d'=' -f2)"
VERSION_NAME="$(grep -E '^app.versionName=' "$ROOT_DIR/gradle.properties" | cut -d'=' -f2)"

if command -v git >/dev/null 2>&1; then
  GIT_SHA="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
else
  GIT_SHA="unknown"
fi

SHA256="$(sha256sum "$COPIED_AAB" | awk '{print $1}')"

cat > "$OUT_DIR/metadata.txt" <<EOF
releaseTimestamp=$STAMP
versionCode=$VERSION_CODE
versionName=$VERSION_NAME
gitSha=$GIT_SHA
artifact=app-release.aab
sha256=$SHA256
EOF

# ── Generate Markdown test report ────────────────────────────────────────────
REPORTS_DIR="$ROOT_DIR/test-reports"
mkdir -p "$REPORTS_DIR"
REPORT_MD="$REPORTS_DIR/v${VERSION_NAME}-${STAMP}.md"

parse_module_results() {
  local xml_dir="$1"
  # Returns: "<tests> <failures> <errors> <skipped>"
  if [[ ! -d "$xml_dir" ]]; then echo "0 0 0 0"; return; fi
  python3 - "$xml_dir" <<'PYEOF'
import sys, os, xml.etree.ElementTree as ET
d = sys.argv[1]; t=f=e=s=0
for fn in os.listdir(d):
    if fn.endswith('.xml'):
        r = ET.parse(os.path.join(d, fn)).getroot()
        t += int(r.get('tests',0)); f += int(r.get('failures',0))
        e += int(r.get('errors',0)); s += int(r.get('skipped',0))
print(t, f, e, s)
PYEOF
}

read -r CORE_T CORE_F CORE_E CORE_S <<< \
  "$(parse_module_results "$ROOT_DIR/core/build/test-results/test")"
read -r APP_T  APP_F  APP_E  APP_S  <<< \
  "$(parse_module_results "$ROOT_DIR/app/build/test-results/testDebugUnitTest")"

TOTAL_FAIL=$(( CORE_F + CORE_E + APP_F + APP_E ))
if [[ "$TOTAL_FAIL" -eq 0 ]]; then
  VERDICT="✅ All tests passed — ok to release."
else
  VERDICT="❌ ${TOTAL_FAIL} test(s) failed — do NOT release."
fi

cat > "$REPORT_MD" <<MDEOF
# Test report – v${VERSION_NAME} ($(date '+%Y-%m-%d'))

| Field | Value |
|---|---|
| Version | ${VERSION_NAME} (code ${VERSION_CODE}) |
| Git SHA | ${GIT_SHA} |
| Built | ${STAMP} |

## Results

| Module | Tests | Failures | Errors | Skipped |
|---|---|---|---|---|
| \`:core\` | ${CORE_T} | ${CORE_F} | ${CORE_E} | ${CORE_S} |
| \`:app\` | ${APP_T} | ${APP_F} | ${APP_E} | ${APP_S} |

## Verdict

${VERDICT}

---
*Generated by \`scripts/release-local.sh\`. Do not edit manually.*
MDEOF

echo "==> Test report written to $REPORT_MD"

echo "==> Release artifacts prepared"
echo "    Bundle:      $COPIED_AAB"
echo "    Metadata:    $OUT_DIR/metadata.txt"
echo "    Test report: $REPORT_MD"
echo ""
echo "Next steps:"
echo "  1. Review $REPORT_MD and commit it:  git add test-reports/ && git commit -m 'chore: test report v${VERSION_NAME}'"
echo "  2. Upload $COPIED_AAB to Google Play Console (internal testing first)."

